baseurl = "http://www.alberts.me"
theme = "redlounge"
languageCode = "en-us"
title = "John Alberts' Blog"
author = "John Alberts"
disqusShortname = "alberts"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
[indexes]
  category = "categories"
canonifyurls = true

[Params]
  nodate = true
  socialsharing = true
  sidebartitle = "John Alberts' Blog"
  description = "Random Thoughts"
  AuthorName = "John"
  github = "albertsj1"
  bitbucket = "jalberts"
  twitter = "alberts"
  email = "john@alberts.me"
  linkedin = "johnmalberts"
  logo = "/img/me.jpg"

[[menu.social]]
  pre = "<i class='fa fa-twitter'></i>"
  url = "http://www.twitter.com/alberts"
  identifier = "twitter"
    
[[menu.social]]
  pre = "<i class='fa fa-github'></i>"
  url = "http://github.com/albertsj1"
  identifier = "github"

[[menu.social]]
  pre = "<i class='fa fa-linkedin'></i>"
  url = "http://www.linkedin.com/in/johnmalberts/en"
  identifier = "linkedin"
