baseurl = "http://www.alberts.me"
theme = "blackburn"
languageCode = "en-us"
title = "John Alberts' Blog"
author = "John Alberts"
disqusShortname = "alberts"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
paginate = 10
disableKinds = ["RSS"]
enableRobotsTXT = true
enableEmoji = true

[outputs]
  home = ["HTML"]

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  brand = "Home"
  disqus = "alberts"
  googleAnalytics = "UA-113453795-1"
  nodate = true
  socialsharing = true
  sidebartitle = "John Alberts' Blog"
  description = "Random Thoughts"
  AuthorName = "John"
  highlightjs = "androidstudio"

[social]
  github = "albertsj1"
  bitbucket = "jalberts"
  twitter = "alberts"
  email = "john@alberts.me"
  linkedin = "johnmalberts"
  lastfm = "albertsj1"
  hackernews = "jalberts72"
  keybase = "jalberts"
  steam = "john_alberts"

[menu]

  [[menu.main]]
    name = "Subscribe"
    weight = 1
  [[menu.main]]
      name = "  FeedBurner"
      pre = "<i class='fa fa-feed fa-fw'></i>"
      weight = 10
      identifier = "FeedBurner"
      url = "http://feeds.feedburner.com/JohnAlbertsBlog"
      
  [[menu.main]]
      name = "  Email Updates"
      pre = "<i class='fa fa-updates fa-fw'></i>"
      weight = 20
      url = "https://feedburner.google.com/fb/a/mailverify?uri=JohnAlbertsBlog&amp;loc=en_US"
      identifier = "Get-Email-Updates"
